config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("course_ng.users.urls", namespace="users")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("accounts/", include("allauth.urls")),
    path("invitations/", include('invitations.urls', namespace='invitations')),
    path("i18n/", include("django.conf.urls.i18n")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

course_ng/users/urls.py
from django.urls import path

from course_ng.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

courses/urls.py
from django.urls import path, re_path

from courses.views import (CourseCreateView, CourseDeleteView, CourseListView, CourseUpdateView,
                           course_detail_view, CourseReviewCreateView, CourseReviewUpdateView)
from courses.autocomplete import LecturerAutoComplete

app_name = "courses"
urlpatterns = [
    # path("", CourseHomePageView.as_view(), name="courses"),
    path("", CourseListView.as_view(), name="courses"),
    path("~add/", CourseCreateView.as_view(), name="course-add"),
    path("<int:pk>/~update/", CourseUpdateView.as_view(), name="course-update"),
    path("<int:pk>/", course_detail_view, name="course-detail"),
    path("<int:pk>/~delete/", CourseDeleteView.as_view(), name="course-delete"),
    path("<int:pk>/~add-review", CourseReviewCreateView.as_view(), name="create-course-review"),
    path("review/<int:pk>/~update/", CourseReviewUpdateView.as_view(), name="update-course-review"),
    re_path(r'^lecturer-autocomplete/$', LecturerAutoComplete.as_view(), name='lecturer-autocomplete',
    ),
]

course_ng/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from course_ng.users.managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for Course NG.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255,
                     help_text=_("input your preferred display name, this name will show under your reviews."))
    department = CharField(_("Study Department"), blank=True, max_length=255)
    major = CharField(_("Study Major"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

course_ng/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

course_ng/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name", "department", "major"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

course_ng/templates/users/user_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}
  User:
  {{ object.name }}
{% endblock title %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h4>{% if object.name %}{{ object.name }}{% else %}{% translate "(Name of user is not setup)" %}{% endif %}</h4>
        <ul>
          <li>{% translate 'Department' %}: {{ object.department }}</li>
          <li>{% translate 'Major' %}: {{ object.major }}</li>
        </ul>
      </div>
    </div>
    {% if object == request.user %}
      <!-- Action buttons -->
      <div class="row">
        <div class="col-sm-12">
          <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">{% translate "Update Info" %}</a>
          <a class="btn btn-primary"
             href="{% url 'account_email' %}"
             role="button">{% translate "E-Mail" %}</a>
          <!-- Your Stuff: Custom user template urls -->
        </div>
      </div>
      <!-- End Action buttons -->
      <hr>
      <div class="row">
        <h4>{% translate 'Review History' %}</h4>
        <table class="table table-striped">
          <thead>
          <tr>
            <th scope="col">{% translate 'Overall Grade' %}</th>
            <th scope="col">{% translate 'Course' %}</th>
            <th scope="col">{% translate 'Review Time' %}</th>
            <th scope="col">{% translate 'Tool' %}</th>
          </tr>
          </thead>
          <tbody>
          {% for review in object.reviewer_reviews.all %}
            <tr>
              <th scope="row">{{ review.overall_grade }}</th>
              <td>{{ review.course }}</td>
              <td>{{ review.submit_date }}</td>
              <td><a href="{% url 'courses:course-detail' review.course.id %}">{% translate 'Course Page' %}</a> <a
                href="{% url 'courses:update-course-review' review.id %}">{% translate 'Edit Review' %}</a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>

      </div>
    {% endif %}
  </div>
{% endblock content %}

course_ng/templates/users/user_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  {{ user.name }}
{% endblock title %}
{% block content %}
  <h1>{{ user.name }}</h1>
  <form class="form-horizontal"
        method="post"
        action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock content %}