config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("course_ng.users.urls", namespace="users")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("accounts/", include("allauth.urls")),
    path("invitations/", include('invitations.urls', namespace='invitations')),
    path("i18n/", include("django.conf.urls.i18n")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

course_ng/users/urls.py
from django.urls import path

from course_ng.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

courses/urls.py
from django.urls import path, re_path

from courses.views import (CourseCreateView, CourseDeleteView, CourseListView, CourseUpdateView,
                           course_detail_view, CourseReviewCreateView, CourseReviewUpdateView)
from courses.autocomplete import LecturerAutoComplete

app_name = "courses"
urlpatterns = [
    # path("", CourseHomePageView.as_view(), name="courses"),
    path("", CourseListView.as_view(), name="courses"),
    path("~add/", CourseCreateView.as_view(), name="course-add"),
    path("<int:pk>/~update/", CourseUpdateView.as_view(), name="course-update"),
    path("<int:pk>/", course_detail_view, name="course-detail"),
    path("<int:pk>/~delete/", CourseDeleteView.as_view(), name="course-delete"),
    path("<int:pk>/~add-review", CourseReviewCreateView.as_view(), name="create-course-review"),
    path("review/<int:pk>/~update/", CourseReviewUpdateView.as_view(), name="update-course-review"),
    re_path(r'^lecturer-autocomplete/$', LecturerAutoComplete.as_view(), name='lecturer-autocomplete',
    ),
]

courses/models.py
from ckeditor.fields import RichTextField
from ckeditor.widgets import CKEditorWidget
from django.db import models
from django.forms import CharField, ModelForm
# from django.utils.functional import lazy
from django.db.models import UniqueConstraint, Q
from django.utils.translation import gettext_lazy as _

from course_ng.users.models import User

MAPPING = {
    'A': 4.0,
    'B': 3.0,
    'C': 2.0,
    'D': 1.0,
    'F': 0.0,
}


def digit_grade_to_letter(grade_sum):
    if grade_sum > 3.9:
        return 'A+'
    elif grade_sum >= 3.75:
        return 'A'
    elif grade_sum >= 3.5:
        return 'A-'
    elif grade_sum >= 3.25:
        return 'B+'
    elif grade_sum >= 3.0:
        return 'B'
    elif grade_sum >= 2.75:
        return 'B-'
    elif grade_sum >= 2.5:
        return 'C+'
    elif grade_sum >= 2.0:
        return 'C'
    elif grade_sum >= 1.75:
        return 'C-'
    elif grade_sum >= 1.5:
        return 'D+'
    elif grade_sum >= 1.0:
        return 'D'
    else:
        return 'F'


class Course(models.Model):
    COURSE_TYPE = [
        ("NR", _("No Record")),
        ("MR", _("Major Required")),
        ("ME", _("Major Elective")),
        ("GE", _("General Education")),
        ("UC", _("University Core")),
        ("FE", _("Free Elective")),
        ("BBA", _("BBA (Hons) Core")),
        ("CR", _("Concentration Required")),
        ("MX", _("Mixed Type (Check Notes For Detail)"))
    ]
    course_code = models.CharField(_("Course Code"), max_length=32)
    course_name_en = models.CharField(_("Course English Name"), max_length=128)
    course_name_cn = models.CharField(_("Course Chinese Name"), max_length=128, blank=True)
    course_units = models.IntegerField(_("Course Credit"), default=3)
    course_prerequisites = models.CharField(_("Course Prerequisites"), default="", blank=True)
    course_exclusions = models.CharField(_("Course Exclusions"), default="", blank=True)
    course_type = models.CharField(_("Course Type"), max_length=10, choices=COURSE_TYPE, default="NR")
    course_description = RichTextField(verbose_name=_("Course Description"), blank=True, default='')
    is_visible = models.BooleanField(_("Visibility of the course"), default=True)
    update_time = models.DateTimeField(_("Course information update time"), auto_now=True)

    def __str__(self):
        return f"{self.course_code} {self.course_name_en}"

    @property
    def overall_grade(self):
        reviews = self.course_reviews.all()
        if not reviews:
            return {'content': 'N/A', 'teaching': 'N/A', 'grading': 'N/A', 'workload': 'N/A'}

        content_grade_sum = 0
        teaching_grade_sum = 0
        grading_grade_sum = 0
        workload_grade_sum = 0

        for review in reviews:
            content_grade_sum += MAPPING[review.content_grade]
            teaching_grade_sum += MAPPING[review.teaching_grade]
            grading_grade_sum += MAPPING[review.grading_grade]
            workload_grade_sum += MAPPING[review.workload_grade]

        content_grade_sum /= len(reviews)
        teaching_grade_sum /= len(reviews)
        grading_grade_sum /= len(reviews)
        workload_grade_sum /= len(reviews)

        return {'content': digit_grade_to_letter(content_grade_sum),
                'teaching': digit_grade_to_letter(teaching_grade_sum),
                'grading': digit_grade_to_letter(grading_grade_sum),
                'workload': digit_grade_to_letter(workload_grade_sum)}


class CourseNote(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="notes")
    note = models.CharField(_("Course Note"), max_length=500)
    update_time = models.DateTimeField(auto_now=True)


class Lecturer(models.Model):
    name = models.CharField(verbose_name="Lecturer Name")
    alternative_name = models.CharField(verbose_name="Alternative Name", blank=True)
    faculties = models.CharField(verbose_name="Lecturer Faculties", blank=True)
    url = models.URLField(verbose_name="Lecturer Homepage URL", blank=True)
    is_resigned = models.BooleanField(default=False, verbose_name="The lecturer is resigned from the college")

    def __str__(self):
        return self.name


LETTER_GRADE = [
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('F', 'F')
]

SEMESTER = [
    ('NOTSPEC', 'Not Specified'),
    # ('23-24-4', '2023-2024 Summer'),
    # ('23-24-3', '2023-2024 Spring'),
    # ('23-24-2', '2023-2024 Winter'),
    ('23-24-1', '2023-2024 Fall'),
    ('22-23-4', '2022-2023 Summer'),
    ('22-23-3', '2022-2023 Spring'),
    ('22-23-2', '2022-2023 Winter'),
    ('22-23-1', '2022-2023 Fall'),
    ('21-22-4', '2021-2022 Summer'),
    ('21-22-3', '2021-2022 Spring'),
    ('21-22-2', '2021-2022 Winter'),
    ('21-22-1', '2021-2022 Fall'),
    ('20-21-4', '2020-2021 Summer'),
    ('20-21-3', '2020-2021 Spring'),
    ('20-21-2', '2020-2021 Winter'),
    ('20-21-1', '2020-2021 Fall'),
    ('19-20-4', '2019-2020 Summer'),
    ('19-20-3', '2019-2020 Spring'),
    ('19-20-2', '2019-2020 Winter'),
    ('19-20-1', '2019-2020 Fall'),
]


class Review(models.Model):
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("Reviewer"),
                                 related_name="reviewer_reviews",
                                 help_text=_("Comments will only display the UID or nickname set by the user, "
                                             "and other information (such as email) will not be displayed in the "
                                             "webpage."))
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="course_reviews",
                               verbose_name=_("Review Course"))
    semester = models.CharField(_("Semester"), choices=SEMESTER, default="NOTSPEC")
    summary = models.CharField(_("Short Review Summary"), max_length=100)
    lecturer = models.ManyToManyField(Lecturer, verbose_name=_("Lecturer"), blank=True)
    content = models.TextField(_("Content Comment"), blank=True)
    content_grade = models.CharField(verbose_name="Content Letter Grade", choices=LETTER_GRADE, default='C')
    teaching = models.TextField(_("Teaching Comment"), blank=True)
    teaching_grade = models.CharField(verbose_name="Teaching Letter Grade", choices=LETTER_GRADE, default='C')
    grading = models.TextField(_("Grading Comment"), blank=True)
    grading_grade = models.CharField(verbose_name="Grading Letter Grade", choices=LETTER_GRADE, default='C')
    workload = models.TextField(_("Workload Comment"), blank=True)
    workload_grade = models.CharField(verbose_name="Workload Letter Grade", choices=LETTER_GRADE, default='C')
    mid_term = models.BooleanField(_("Has Mid-term"), default=False)
    final_exam = models.BooleanField(_("Has Final Exam"), default=True)
    quiz = models.BooleanField(_("Has Quiz"), default=False)
    assignment = models.BooleanField(_("Has Assignment"), default=False)
    essay = models.BooleanField(_("Has Essay"), default=False)
    project = models.BooleanField(_("Has Project"), default=False)
    attendance = models.BooleanField(_("Has Attendance"), default=False)
    reading_material = models.BooleanField(_("Has Reading Material"), default=False)
    presentation = models.BooleanField(_("Has Presentation"), default=False)
    submit_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.reviewer.email} review on {self.course.course_code}'

    class Meta:
        constraints = [
            UniqueConstraint(fields=('reviewer', 'course'), name='one_review_per_course_for_an_user'),
        ]

    @property
    def overall_score_grade(self):
        grade_sum = 0

        grade_sum += MAPPING[self.content_grade]
        grade_sum += MAPPING[self.teaching_grade]
        grade_sum += MAPPING[self.grading_grade]
        grade_sum += MAPPING[self.workload_grade]
        grade_sum /= 4

        return grade_sum

    @property
    def overall_grade(self):
        return digit_grade_to_letter(self.overall_score_grade)

course_ng/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name", "department", "major"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from braces.views import SuperuserRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView
from django.contrib import messages
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
import datetime

from courses.models import Course, Review
from courses.forms import CourseForm, ReviewForm
from courses.filters import CourseFilterSet


class CourseListView(ListView):
    filter_set = CourseFilterSet
    model = Course
    paginate_by = 15
    template_name = 'pages/courses_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = self.filter_set(self.request.GET, queryset=queryset)
        # Return the filtered queryset
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filter_set(self.request.GET, queryset=self.get_queryset())
        return context


class CourseHomePageView(TemplateView):
    template_name = "pages/courses.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["courses"] = Course.objects.all()[:10]
        return context


class CourseDetailView(DetailView):
    model = Course
    slug_field = "id"
    slug_url_kwarg = "id"

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        context['current_user_reviewed'] = Review.objects.filter(course=self.object.id, reviewer=self.request.user.id).exists()
        return context


course_detail_view = CourseDetailView.as_view()


class CourseCreateView(SuperuserRequiredMixin, CreateView):
    template_name = "courses/course_form.html"
    model = Course
    success_url = reverse_lazy("home")
    form_class = CourseForm


class CourseUpdateView(SuperuserRequiredMixin, UpdateView):
    template_name = "courses/course_edit_form.html"
    model = Course
    fields = "__all__"

    def get_success_url(self):
        course_id = self.kwargs["pk"]
        return reverse_lazy("courses:course-detail", kwargs={"pk": course_id})


class CourseDeleteView(LoginRequiredMixin, SuperuserRequiredMixin, DeleteView):
    template_name = "courses/course_confirm_delete.html"
    model = Course
    success_url = reverse_lazy("courses:courses")


# Create your views here.
class CourseReviewCreateView(LoginRequiredMixin, CreateView):
    course_id = None
    template_name = "courses/course_review_form.html"
    model = Review
    form_class = ReviewForm

    def get_initial(self):
        return {
            'reviewer': self.request.user,
            'course': self.kwargs['pk']
        }

    def form_valid(self, form):
        form.instance.reviewer = self.request.user
        return super(CourseReviewCreateView, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CourseReviewCreateView, self).get_context_data(**kwargs)
        context['review_course'] = Course.objects.get(pk=self.kwargs['pk'])
        context['course_id'] = self.kwargs['pk']
        return context

    def get_success_url(self):
        return reverse_lazy('courses:course-detail', kwargs={'pk': self.kwargs.get('pk')})


class CourseReviewUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "courses/course_review_edit_form.html"
    model = Review
    form_class = ReviewForm

    def test_func(self):
        if self.get_object().submit_date > timezone.now() - datetime.timedelta(days=7):
            messages.add_message(self.request,
                                 messages.INFO,
                                 _("Review is allow to update within 7 days after you initial submit."))
        else:
            messages.add_message(self.request,
                                 messages.WARNING,
                                 _("Review is not allow to update after 7 days since your initial submit."))
            return False
        return self.request.user == self.get_object().reviewer

    def get_context_data(self, **kwargs):
        context = super(CourseReviewUpdateView, self).get_context_data(**kwargs)
        context['review'] = Review.objects.get(pk=self.kwargs['pk'])
        return context

    def get_success_url(self):
        review_id = self.kwargs["pk"]
        rv = Review.objects.get(pk=review_id)
        return reverse_lazy("courses:course-detail", kwargs={"pk": rv.course.id})

course_ng/templates/courses/course_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {% translate 'Delete Course' %}{{ course.course_code }} {{ course.course_name_en }}
{% endblock title %}
{% block content %}
  <form method="post">{% csrf_token %}
<h1>{% blocktrans %}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}</h1>
  <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-danger">{% translate 'Delete' %}</button>
      </div>
    </div>
</form>
  <hr>
<h3>{% translate 'Course Detail' %}</h3>
  <h4>{{ course.course_name_cn }}</h4>
  <p>
    {% translate 'Prerequisites' %}: {{ course.course_prerequisites }}, Type: {{ course.course_type }}, Unit(s): {{ course.course_units }}
  </p>
  <hr/>
  {% translate 'Course Description' %}
  {{ course.course_description | safe }}
{% endblock content %}

course_ng/templates/courses/course_edit_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% translate 'Edit Course' %} :: {{ course.course_code }}
{% endblock title %}
{% block content %}
  <h1>{% translate 'Edit Course' %} :: {{ course.course_code }}</h1>
  <form class="form-horizontal"
        method="post"
        action="{% url 'courses:course-update' course.id %}">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">{% translate 'Submit' %}</button>
      </div>
    </div>
  </form>
{% endblock content %}

course_ng/templates/courses/course_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {% translate 'New Course' %}
{% endblock title %}
{% block content %}
  <h1>{% translate 'New Course' %}</h1>
  <form class="form-horizontal"
        method="post"
        action="{% url 'courses:course-add' %}">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">{% translate 'Submit' %}</button>
      </div>
    </div>
  </form>
{% endblock content %}

course_ng/templates/courses/course_review_edit_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ user.name }}
{% endblock title %}
{% block content %}
  <h1>{% translate 'Update Review' %}</h1>
  <h2>{{ review.course.course_code }} {{ review.course.course_name_en }}</h2>
  <p>
    {% translate 'Prerequisites' %}: {{ review.course.course_prerequisites }}, Type: {{ review.course.get_course_type_display }}, Unit(s): {{ review.course.course_units }}
  </p>
  <p>{% translate 'Course Description' %}: {{ review.course.course_description | safe }}</p>
  <hr />

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.js" integrity="sha512-+k1pnlgt4F1H8L7t3z95o3/KO+o78INEcXTbnoJQ/F2VqDVhWoaiVml/OEHv9HsVgxUaVW+IbiZPUJQfF/YxZw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <form class="form-horizontal"
        method="post"
        action="{% url 'courses:update-course-review' review.id %}">
    {% csrf_token %}
    {{ form.media }}
{#    {{ form|crispy }}#}
    {% crispy form %}
{#    <div class="control-group">#}
{#      <div class="controls">#}
{#        <button type="submit" class="btn btn-primary">Update</button>#}
{#      </div>#}
{#    </div>#}
  </form>
  <script>
(function($) {
    $('#add-form').click(function() {
        var index = $('#id_inline_test_models-TOTAL_FORMS').val()
        var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
        newTable.find(':input').each(function() {
            for (attr of ['name', 'id'])
                $(this).attr(
                    attr,
                    $(this).attr(attr).replace('__prefix__', index)
                )
        })
        newTable.insertBefore($(this))
        $('#id_inline_test_models-TOTAL_FORMS').val(
            parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
        )
        newTable.slideDown()
    })
})($)
</script>
{% endblock content %}

course_ng/templates/courses/course_review_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ user.name }}
{% endblock title %}
{% block content %}
  <h1>{% translate 'New Review' %}</h1>
  <h2>{{ review_course.course_code }} {{ review_course.course_name_en }}</h2>
  <p>
    {% translate 'Prerequisites' %}: {{ review_course.course_prerequisites }}, Type: {{ review_course.get_course_type_display }}, Unit(s): {{ review_course.course_units }}
  </p>
  <p>{% translate 'Course Description' %}: {{ review_course.course_description | safe }}</p>
  <hr />

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.js" integrity="sha512-+k1pnlgt4F1H8L7t3z95o3/KO+o78INEcXTbnoJQ/F2VqDVhWoaiVml/OEHv9HsVgxUaVW+IbiZPUJQfF/YxZw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <form class="form-horizontal"
        method="post"
        action="{% url 'courses:create-course-review' course_id %}">
    {% csrf_token %}
    {{ form.media }}
{#    {{ form|crispy }}#}
    {% crispy form %}
{#    <div class="control-group">#}
{#      <div class="controls">#}
{#        <button type="submit" class="btn btn-primary">Create</button>#}
{#      </div>#}
{#    </div>#}
  </form>
  <script>
(function($) {
    $('#add-form').click(function() {
        var index = $('#id_inline_test_models-TOTAL_FORMS').val()
        var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
        newTable.find(':input').each(function() {
            for (attr of ['name', 'id'])
                $(this).attr(
                    attr,
                    $(this).attr(attr).replace('__prefix__', index)
                )
        })
        newTable.insertBefore($(this))
        $('#id_inline_test_models-TOTAL_FORMS').val(
            parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
        )
        newTable.slideDown()
    })
})($)
</script>
{% endblock content %}