config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("course_ng.users.urls", namespace="users")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("accounts/", include("allauth.urls")),
    path("invitations/", include('invitations.urls', namespace='invitations')),
    path("i18n/", include("django.conf.urls.i18n")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

course_ng/users/urls.py
from django.urls import path

from course_ng.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

courses/urls.py
from django.urls import path, re_path

from courses.views import (CourseCreateView, CourseDeleteView, CourseListView, CourseUpdateView,
                           course_detail_view, CourseReviewCreateView, CourseReviewUpdateView)
from courses.autocomplete import LecturerAutoComplete

app_name = "courses"
urlpatterns = [
    # path("", CourseHomePageView.as_view(), name="courses"),
    path("", CourseListView.as_view(), name="courses"),
    path("~add/", CourseCreateView.as_view(), name="course-add"),
    path("<int:pk>/~update/", CourseUpdateView.as_view(), name="course-update"),
    path("<int:pk>/", course_detail_view, name="course-detail"),
    path("<int:pk>/~delete/", CourseDeleteView.as_view(), name="course-delete"),
    path("<int:pk>/~add-review", CourseReviewCreateView.as_view(), name="create-course-review"),
    path("review/<int:pk>/~update/", CourseReviewUpdateView.as_view(), name="update-course-review"),
    re_path(r'^lecturer-autocomplete/$', LecturerAutoComplete.as_view(), name='lecturer-autocomplete',
    ),
]

course_ng/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from course_ng.users.managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for Course NG.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255,
                     help_text=_("input your preferred display name, this name will show under your reviews."))
    department = CharField(_("Study Department"), blank=True, max_length=255)
    major = CharField(_("Study Major"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

course_ng/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

course_ng/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name", "department", "major"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

course_ng/templates/pages/courses.html
{% extends "base.html" %}

{% block content %}
  <div class="row my-5">
    <div class="col-4">
      <div class="list-group">
        <span class="list-group-item list-group-item-action list-group-item-success">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Faculty of Business and Management</h5>
            <small>FBM</small>
          </div>
          <p class="mb-1">工商管理学院</p>
          <small>7 Programmes</small>
        </span>
        <a class="list-group-item">ACCT: Accounting</a>
        <a class="list-group-item">FIN: Finance</a>
        <a class="list-group-item">AE: Applied Economic</a>
        <a class="list-group-item">MHR: Management of Human Resources</a>
        <a class="list-group-item">MKT: Marketing Management</a>
        <a class="list-group-item">EBIS: e-Business Management and Information Systems</a>
        <a class="list-group-item">DMM: Digital Media Management</a>
        <span class="list-group-item list-group-item-action list-group-item-dark">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">School of Culture and Creativity</h5>
            <small>SCC</small>
          </div>
          <p class="mb-1">文化与创意学院</p>
          <small>5 Programmes</small>
        </span>
        <a class="list-group-item">CCM: Culture, Creativity and Management</a>
        <a class="list-group-item">MAD: Media Arts and Design</a>
        <a class="list-group-item">THEM: Tourism, Hospitality and Event Management</a>
        <a class="list-group-item">AIM: Animation and Interactive Media</a>
        <a class="list-group-item">MUS: Music Performance</a>
        <span href="#"
              class="list-group-item list-group-item-action list-group-item-warning">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Faculty of Humanities and Social Science</h5>
            <small>FHSS</small>
          </div>
          <p class="mb-1">人文社科学院</p>
          <small>8 Programmes</small>
        </span>
        <a class="list-group-item">CCGC</a>
        <a class="list-group-item">MCOM</a>
        <a class="list-group-item">PRA</a>
        <a class="list-group-item">ATS</a>
        <a class="list-group-item">ELLS</a>
        <a class="list-group-item">DSS</a>
        <a class="list-group-item">GAD</a>
        <a class="list-group-item">SWSA</a>
        <span href="#"
              class="list-group-item list-group-item-action list-group-item-primary">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Faculty of Science and Technology</h5>
            <small>FST</small>
          </div>
          <p class="mb-1">理工科技学院</p>
          <small>9 Programmes</small>
        </span>
        <a class="list-group-item">AM</a>
        <a class="list-group-item">FM</a>
        <a class="list-group-item">STAT</a>
        <a class="list-group-item">DS</a>
        <a class="list-group-item">AI</a>
        <a class="list-group-item">CST</a>
        <a class="list-group-item">ENVS</a>
        <a class="list-group-item">FST</a>
        <a class="list-group-item">APSY</a>
      </div>
    </div>
    <div class="col-8">
      <h2>
        Courses <a href="{% url 'courses:course-add' %}">+</a>
      </h2>
      <ul>
        {% for course in courses %}
          <li>
            <a href="{% url 'courses:course-detail' course.id %}">{{ course.course_code }} - {{ course.course_name_en }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock content %}

course_ng/templates/pages/courses_list.html
{% extends "base.html" %}
{% load my_tags %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
  <div class="row my-5">
    <div class="col-md-9">
      <h2>{% translate "Courses" %}</h2>
<div class="list-group">
          {% for course in object_list %}
            <a href="{% url 'courses:course-detail' course.id %}" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <div><strong>{{ course.course_code }}</strong> <span class="text-secondary">{{ course.course_name_en }}</span></div>
      <small><span class="badge {% if course.course_reviews.all|length > 0 %}bg-success{% else %}bg-secondary{% endif %} rounded-pill">{{ course.course_reviews.all|length }} {% translate "review(s)" %}</span></small>
    </div>
    <span class="text-secondary"><small>{{ course.course_name_cn }}</small></span>
  </a>
          {% endfor %}
</div>
      {% if is_paginated %}
        <div class="mt-3">
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?{% param_replace page=1 %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-chevron-double-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd"
                        d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
                  <path fill-rule="evenodd"
                        d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
                </svg>
              </a></li>
              {% if page_obj.previous_page_number != 1 %}
                <li class="page-item"><a class="page-link"
                                         href="?{% param_replace page=page_obj.previous_page_number %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                       class="bi bi-chevron-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
                  </svg>
                </a>
                </li>
              {% endif %}
            {% endif %}
            <li class="page-item active" aria-current="page">
              <a class="page-link" href="#">{{ page_obj.number }} / {{ paginator.num_pages }}</a>
            </li>
            {% if page_obj.has_next %}
              {% if page_obj.next_page_number != paginator.num_pages %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                       class="bi bi-chevron-right" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
                  </svg>
                </a>
                </li>
              {% endif %}
              <li class="page-item"><a class="page-link" href="?{% param_replace page=paginator.num_pages %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-chevron-double-right" viewBox="0 0 16 16">
                  <path fill-rule="evenodd"
                        d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708"/>
                  <path fill-rule="evenodd"
                        d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708"/>
                </svg>
              </a>
              </li>
            {% endif %}
          </ul>
        </nav>
        </div>
        <p>{% translate "Course" %} {{ page_obj.start_index }}&mdash;{{ page_obj.end_index }} ({% translate 'Total' %}: {{ page_obj.paginator.count }})</p>
      {% endif %}

    </div>
    <div class="col-md-3">
      <h2>{% translate "Filter" %}</h2>
      <form class="form-horizontal" action="" method="get">
        {{ filter.form|crispy }}
        <div class="control-group">
          <div class="controls">
            <input type="submit" class="btn btn-primary"/>
            <a class="btn btn-outline-secondary" href="{%  url 'courses:courses' %}">{% translate "Clear filters" %}</a>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

course_ng/templates/pages/home.html
{% extends "base.html" %}

{% block content %}
  <div class="mt-5">
    <h1>Course NG Welcome!</h1>
    <p>Testflight, no guarantee.</p>
  </div>
  <div class="row">
    <div class="col-lg-4">
      <h5>Latest Reviewed Course</h5>
      <ol class="list-group list-group-numbered">
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Subheading</div>
            Content for list item
          </div>
          <span class="badge bg-primary rounded-pill">14</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Subheading</div>
            Content for list item
          </div>
          <span class="badge bg-primary rounded-pill">14</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Subheading</div>
            Content for list item
          </div>
          <span class="badge bg-primary rounded-pill">14</span>
        </li>
      </ol>
    </div>
    <div class="col-lg-4">
      <h5>Popular Course</h5>
      <ol class="list-group list-group-numbered">
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Subheading</div>
            Content for list item
          </div>
          <span class="badge bg-primary rounded-pill">14</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Subheading</div>
            Content for list item
          </div>
          <span class="badge bg-primary rounded-pill">14</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Subheading</div>
            Content for list item
          </div>
          <span class="badge bg-primary rounded-pill">14</span>
        </li>
      </ol>
    </div>
    <div class="col-lg-4">
      <h5>Best Review Course</h5>
      <ol class="list-group list-group-numbered">
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Subheading</div>
            Content for list item
          </div>
          <span class="badge bg-primary rounded-pill">14</span>
        </li>
      </ol>
    </div>
  </div>
{% endblock content %}